// <auto-generated>
// Do not edit this file yourself!
//
// This code was generated by Stride Shader Mixin Code Generator.
// To generate it yourself, please install Stride.VisualStudio.Package .vsix
// and re-save the associated .sdfx.
// </auto-generated>

using System;
using Stride.Core;
using Stride.Rendering;
using Stride.Graphics;
using Stride.Shaders;
using Stride.Core.Mathematics;
using Buffer = Stride.Graphics.Buffer;

namespace TR.Stride.Atmosphere
{
    public static partial class BlueNoiseKeys
    {
        public static readonly ObjectParameterKey<Buffer> sobol_256spp_256d = ParameterKeys.NewObject<Buffer>();
        public static readonly ObjectParameterKey<Buffer> rankingTile = ParameterKeys.NewObject<Buffer>();
        public static readonly ObjectParameterKey<Buffer> scramblingTile = ParameterKeys.NewObject<Buffer>();
    }
}
