// <auto-generated>
// Do not edit this file yourself!
//
// This code was generated by Stride Shader Mixin Code Generator.
// To generate it yourself, please install Stride.VisualStudio.Package .vsix
// and re-save the associated .sdfx.
// </auto-generated>

using System;
using Stride.Core;
using Stride.Rendering;
using Stride.Graphics;
using Stride.Shaders;
using Stride.Core.Mathematics;
using Buffer = Stride.Graphics.Buffer;

namespace TR.Stride.Atmosphere
{
    public static partial class CloudReconstructKeys
    {
        public static readonly ObjectParameterKey<Texture> CloudReconstructionTexture = ParameterKeys.NewObject<Texture>();
        public static readonly ObjectParameterKey<Texture> CloudReconstructionHistoryTexture = ParameterKeys.NewObject<Texture>();
        public static readonly ObjectParameterKey<Texture> CloudColorTexture = ParameterKeys.NewObject<Texture>();
        public static readonly ObjectParameterKey<Texture> CloudDepthTexture = ParameterKeys.NewObject<Texture>();
        public static readonly ObjectParameterKey<Texture> CloudDepthHistoryTexture = ParameterKeys.NewObject<Texture>();
        public static readonly ValueParameterKey<uint> FrameIndex = ParameterKeys.NewValue<uint>();
        public static readonly ObjectParameterKey<Buffer> scramblingTile = ParameterKeys.NewObject<Buffer>();
        public static readonly ValueParameterKey<int> CloudResolutionDivider = ParameterKeys.NewValue<int>();
        public static readonly ValueParameterKey<Matrix> InvViewProjectionMatrix = ParameterKeys.NewValue<Matrix>();
        public static readonly ValueParameterKey<Matrix> ViewProjectionMatrixPrevious = ParameterKeys.NewValue<Matrix>();
        public static readonly ObjectParameterKey<SamplerState> samplerLinearClamp = ParameterKeys.NewObject<SamplerState>();
        public static readonly ObjectParameterKey<SamplerState> samplerLinearPoint = ParameterKeys.NewObject<SamplerState>();
    }
}
