// <auto-generated>
// Do not edit this file yourself!
//
// This code was generated by Stride Shader Mixin Code Generator.
// To generate it yourself, please install Stride.VisualStudio.Package .vsix
// and re-save the associated .sdfx.
// </auto-generated>

using System;
using Stride.Core;
using Stride.Rendering;
using Stride.Graphics;
using Stride.Shaders;
using Stride.Core.Mathematics;
using Buffer = Stride.Graphics.Buffer;

namespace StrideTerrain.Editor.Effects
{
    internal static partial class ShaderMixins
    {
        internal partial class ComputeTerrainLayerEffect  : IShaderMixinBuilder
        {
            public void Generate(ShaderMixinSource mixin, ShaderMixinContext context)
            {

                {
                    var __mixinToCompose__ = (context.GetParam(ComputeTerrainLayerEffectKeys.Layer));
                    var __subMixin = new ShaderMixinSource();
                    context.PushComposition(mixin, "Layer", __subMixin);
                    context.Mixin(__subMixin, __mixinToCompose__);
                    context.PopComposition();
                }

                {
                    var __mixinToCompose__ = (context.GetParam(ComputeTerrainLayerEffectKeys.BlendMode));
                    var __subMixin = new ShaderMixinSource();
                    context.PushComposition(mixin, "BlendMode", __subMixin);
                    context.Mixin(__subMixin, __mixinToCompose__);
                    context.PopComposition();
                }
                context.Mixin(mixin, "ComputeTerrainLayer");
            }

            [System.Runtime.CompilerServices.ModuleInitializer]
            internal static void __Initialize__()

            {
                ShaderMixinManager.Register("ComputeTerrainLayerEffect", new ComputeTerrainLayerEffect());
            }
        }
    }
}
