// <auto-generated>
// Do not edit this file yourself!
//
// This code was generated by Stride Shader Mixin Code Generator.
// To generate it yourself, please install Stride.VisualStudio.Package .vsix
// and re-save the associated .sdfx.
// </auto-generated>

using System;
using Stride.Core;
using Stride.Rendering;
using Stride.Graphics;
using Stride.Shaders;
using Stride.Core.Mathematics;
using Buffer = Stride.Graphics.Buffer;

namespace StrideTerrain.Editor.Effects
{
    public static partial class TerrainLayerKeys
    {
        public static readonly ObjectParameterKey<Texture> InputTexture = ParameterKeys.NewObject<Texture>();
        public static readonly ObjectParameterKey<Texture> OutputTexture = ParameterKeys.NewObject<Texture>();
        public static readonly ValueParameterKey<uint> Resolution = ParameterKeys.NewValue<uint>();
        public static readonly ValueParameterKey<float> InvResolution = ParameterKeys.NewValue<float>();
        public static readonly ValueParameterKey<float> InvSize = ParameterKeys.NewValue<float>();
        public static readonly ValueParameterKey<float> Size = ParameterKeys.NewValue<float>();
        public static readonly ValueParameterKey<float> UnitsPerTexel = ParameterKeys.NewValue<float>();
        public static readonly ValueParameterKey<float> InvUnitsPerTexel = ParameterKeys.NewValue<float>();
        public static readonly ValueParameterKey<float> MaxHeight = ParameterKeys.NewValue<float>();
    }
}
