<Project>
  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
  </PropertyGroup>
  <ItemGroup>
    <PackageVersion Include="CsvHelper" Version="33.0.1" />
    <PackageVersion Include="System.CommandLine" Version="2.0.0-beta4.22272.1" />
    <PackageVersion Include="Hexa.NET.ImGui" Version="2.0.1" />
    <PackageVersion Include="System.Drawing.Common" Version="10.0.1" />
  </ItemGroup>
  <ItemGroup>
    <PackageVersion Include="Stride.Engine" Version="4.4.0-dev" />
    <PackageVersion Include="Stride.Video" Version="4.4.0-dev" />
    <PackageVersion Include="Stride.Physics" Version="4.4.0-dev" />
    <PackageVersion Include="Stride.Navigation" Version="4.4.0-dev" />
    <PackageVersion Include="Stride.Particles" Version="4.4.0-dev" />
    <PackageVersion Include="Stride.UI" Version="4.4.0-dev" />
    <PackageVersion Include="Stride.Graphics" Version="4.4.0-dev" />
    <PackageVersion Include="Stride.TextureConverter" Version="4.4.0-dev" />
    <PackageVersion Include="Stride.Core" Version="4.4.0-dev" />
    <PackageVersion Include="Stride.AssetCompiler" Version="4.4.0-dev" />
  </ItemGroup>
  <ItemGroup>
    <PackageVersion Include="Stride.Editor" Version="4.4.0-dev" />
    <PackageVersion Include="Stride.Core.BuildEngine.Common" Version="4.4.0-dev" />
  </ItemGroup>
</Project>