<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<OutputType>Library</OutputType>
		<AllowUnsafeBlocks>true</AllowUnsafeBlocks>
		<LangVersion>latest</LangVersion>
		<TargetFrameworks>net10.0-windows</TargetFrameworks>
		<Configurations>Debug;Release;DebugExGameEditor</Configurations>
	</PropertyGroup>
	<ItemGroup>
		<PackageReference Include="Hexa.NET.ImGui" />
		<PackageReference Include="Stride.Core" PrivateAssets="contentfiles;analyzers" />
		<PackageReference Include="Stride.Engine" PrivateAssets="contentfiles;analyzers" />
		<PackageReference Include="Stride.AssetCompiler" PrivateAssets="contentfiles; analyzers" IncludeAssets="build; buildtransitive" />
	</ItemGroup>
	<ItemGroup>
		<None Update="Effects\ImGuiShader.sdsl">
			<CopyToOutputDirectory>Never</CopyToOutputDirectory>
		</None>
	</ItemGroup>
</Project>