// <auto-generated>
// Do not edit this file yourself!
//
// This code was generated by Stride Shader Mixin Code Generator.
// To generate it yourself, please install Stride.VisualStudio.Package .vsix
// and re-save the associated .sdfx.
// </auto-generated>

using System;
using Stride.Core;
using Stride.Rendering;
using Stride.Graphics;
using Stride.Shaders;
using Stride.Core.Mathematics;
using Buffer = Stride.Graphics.Buffer;

namespace StrideTerrain.TerrainSystem.Effects
{
    public static partial class ShadowMapReceiverTerrainDrectionalKeys
    {
        public static readonly ValueParameterKey<Vector4> TerrainWorldSize = ParameterKeys.NewValue<Vector4>();
        public static readonly ValueParameterKey<int> UseTerrainShadowMap = ParameterKeys.NewValue<int>(0);
        public static readonly ObjectParameterKey<Texture> TerrainShadowMap = ParameterKeys.NewObject<Texture>();
    }
}
