// <auto-generated>
// Do not edit this file yourself!
//
// This code was generated by Stride Shader Mixin Code Generator.
// To generate it yourself, please install Stride.VisualStudio.Package .vsix
// and re-save the associated .sdfx.
// </auto-generated>

using System;
using Stride.Core;
using Stride.Rendering;
using Stride.Graphics;
using Stride.Shaders;
using Stride.Core.Mathematics;
using Buffer = Stride.Graphics.Buffer;

namespace StrideTerrain.TerrainSystem.Effects
{
    public static partial class TerrainShadowGeneratorKeys
    {
        public static readonly ObjectParameterKey<Texture> ShadowMap = ParameterKeys.NewObject<Texture>();
        public static readonly ValueParameterKey<Vector2> Delta = ParameterKeys.NewValue<Vector2>();
        public static readonly ValueParameterKey<Vector2> XyStep = ParameterKeys.NewValue<Vector2>();
        public static readonly ValueParameterKey<int> IsSteep = ParameterKeys.NewValue<int>();
        public static readonly ValueParameterKey<Vector4> StartXY = ParameterKeys.NewValue<Vector4>();
        public static readonly ValueParameterKey<PerGroupDataStruct> PerGroupData = ParameterKeys.NewValue<PerGroupDataStruct>();
        public static readonly ValueParameterKey<float> HeightDelta = ParameterKeys.NewValue<float>();
        public static readonly ValueParameterKey<uint> ShadowMapToTerrainSize = ParameterKeys.NewValue<uint>();
    }
}
