// <auto-generated>
// Do not edit this file yourself!
//
// This code was generated by Stride Shader Mixin Code Generator.
// To generate it yourself, please install Stride.VisualStudio.Package .vsix
// and re-save the associated .sdfx.
// </auto-generated>

using System;
using Stride.Core;
using Stride.Rendering;
using Stride.Graphics;
using Stride.Shaders;
using Stride.Core.Mathematics;
using Buffer = Stride.Graphics.Buffer;

namespace StrideTerrain.TerrainSystem.Effects
{
    public static partial class TerrainGenerateHeightmapKeys
    {
        public static readonly ObjectParameterKey<Texture> OutputTexture = ParameterKeys.NewObject<Texture>();
        public static readonly ValueParameterKey<uint> OutputSizeToTerrainSize = ParameterKeys.NewValue<uint>();
        public static readonly ValueParameterKey<uint> OutputSize = ParameterKeys.NewValue<uint>();
    }
}
