// <auto-generated>
// Do not edit this file yourself!
//
// This code was generated by Stride Shader Mixin Code Generator.
// To generate it yourself, please install Stride.VisualStudio.Package .vsix
// and re-save the associated .sdfx.
// </auto-generated>

using System;
using Stride.Core;
using Stride.Rendering;
using Stride.Graphics;
using Stride.Shaders;
using Stride.Core.Mathematics;
using Buffer = Stride.Graphics.Buffer;

namespace StrideTerrain.Rendering.Effects
{
    public static partial class CompressBC5Keys
    {
        public static readonly ObjectParameterKey<Texture> InputTexture = ParameterKeys.NewObject<Texture>();
        public static readonly ObjectParameterKey<Texture> OutputTexture = ParameterKeys.NewObject<Texture>();
        public static readonly ValueParameterKey<float> InvTextureWidth = ParameterKeys.NewValue<float>();
        public static readonly ObjectParameterKey<SamplerState> DefaultSampler = ParameterKeys.NewObject<SamplerState>();
    }
}
