// <auto-generated>
// Do not edit this file yourself!
//
// This code was generated by Stride Shader Mixin Code Generator.
// To generate it yourself, please install Stride.VisualStudio.Package .vsix
// and re-save the associated .sdfx.
// </auto-generated>

using System;
using Stride.Core;
using Stride.Rendering;
using Stride.Graphics;
using Stride.Shaders;
using Stride.Core.Mathematics;
using Buffer = Stride.Graphics.Buffer;

namespace StrideTerrain.Rendering.Effects
{
    [DataContract]public partial class RadiancePrefilteringGGXV2Params : ShaderMixinParameters
    {
        public static readonly PermutationParameterKey<uint> NbOfSamplings = ParameterKeys.NewPermutation<uint>();
        public static readonly PermutationParameterKey<uint> BlockSize = ParameterKeys.NewPermutation<uint>();
        public static readonly PermutationParameterKey<uint> ThreadOffload = ParameterKeys.NewPermutation<uint>();
    };
    internal static partial class ShaderMixins
    {
        internal partial class RadiancePrefilteringGGXEffectV2  : IShaderMixinBuilder
        {
            public void Generate(ShaderMixinSource mixin, ShaderMixinContext context)
            {
                context.Mixin(mixin, "RadiancePrefilteringGGXShaderV2", context.GetParam(RadiancePrefilteringGGXV2Params.NbOfSamplings), context.GetParam(RadiancePrefilteringGGXV2Params.BlockSize), context.GetParam(RadiancePrefilteringGGXV2Params.ThreadOffload));
            }

            [System.Runtime.CompilerServices.ModuleInitializer]
            internal static void __Initialize__()

            {
                ShaderMixinManager.Register("RadiancePrefilteringGGXEffectV2", new RadiancePrefilteringGGXEffectV2());
            }
        }
    }
}
