<Project Sdk="Microsoft.NET.Sdk">
	<Import Project="..\Common.props" />

	<PropertyGroup>
		<TargetFramework>net10.0-windows</TargetFramework>
		<RuntimeIdentifier>win-x64</RuntimeIdentifier>
		<ApplicationIcon>Resources\Icon.ico</ApplicationIcon>
		<OutputType>WinExe</OutputType>
		<RootNamespace>StrideTerrain.Editor</RootNamespace>

		<OutputPath>..\Bin\Editor\$(Configuration)\</OutputPath>
		<AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
		
		<Nullable>Enable</Nullable>
		<AllowUnsafeBlocks>true</AllowUnsafeBlocks>

		<!-- Force msbuild to check to rebuild this assembly instead of letting VS IDE guess -->
		<DisableFastUpToDateCheck>true</DisableFastUpToDateCheck>
		<Configurations>Debug;Release;DebugExGameEditor</Configurations>
	</PropertyGroup>

	<ItemGroup>
	  <None Remove="Resources\forkawesome-webfont.ttf" />
	  <None Remove="Resources\JetBrainsMonoNL-Medium.ttf" />
	  <None Remove="Resources\Roboto-Regular.ttf" />
	</ItemGroup>

	<ItemGroup>
	  <EmbeddedResource Include="Resources\forkawesome-webfont.ttf" />
	  <EmbeddedResource Include="Resources\JetBrainsMonoNL-Medium.ttf" />
	  <EmbeddedResource Include="Resources\Roboto-Regular.ttf" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\StrideCommunity.ImGuiDebug\StrideCommunity.ImGuiDebug.csproj" />
		<ProjectReference Include="..\StrideTerrain\StrideTerrain.csproj" />
		<ProjectReference Include="..\TR.Stride.Ocean\TR.Stride.Ocean.csproj" />
	</ItemGroup>

	<ItemGroup>
	  <None Update="Effects\BlendModes\BlendSubtract.sdsl" />
	  <None Update="Effects\BlendModes\BlendMax.sdsl" />
	  <None Update="Effects\BlendModes\BlendAlphaBlend.sdsl" />
	  <None Update="Effects\BlendModes\BlendAdd.sdsl" />
	  <None Update="Effects\BlendModes\BlendMultiply.sdsl" />
	  <None Update="Effects\CalculateNormalMap.sdsl" />
	  <None Update="Effects\ComputeTerrainLayerEffect.sdfx" />
	  <None Update="Effects\EditorTerrainMaterialStreamInitializer.sdsl" />
	  <None Update="Effects\EditorTerrainDiffuse.sdsl" />
	  <None Update="Effects\EditorTerrainDisplacement.sdsl" />
	  <None Update="Effects\ComputeTerrainLayer.sdsl" />
	  <None Update="Effects\Layers\LayerErosion.sdsl" />
	  <None Update="Effects\Layers\LayerGroup.sdsl" />
	  <None Update="Effects\Layers\LayerCircle.sdsl" />
	  <None Update="Effects\TerrainBlendMode.sdsl" />
	  <None Update="Effects\TerrainLayer.sdsl" />
	  <None Update="Effects\Layers\LayerRidged.sdsl" />
	  <None Update="Effects\NoiseBase.sdsl" />
	  <None Update="Effects\Layers\LayerTurbulence.sdsl" />
	  <None Update="Effects\Layers\LayerFbm.sdsl" />
	  <None Update="Effects\Layers\LayerConstantValue.sdsl" />
	</ItemGroup>

</Project>
