// <auto-generated>
// Do not edit this file yourself!
//
// This code was generated by Stride Shader Mixin Code Generator.
// To generate it yourself, please install Stride.VisualStudio.Package .vsix
// and re-save the associated .sdfx.
// </auto-generated>

using System;
using Stride.Core;
using Stride.Rendering;
using Stride.Graphics;
using Stride.Shaders;
using Stride.Core.Mathematics;
using Buffer = Stride.Graphics.Buffer;

namespace StrideTerrain.Vegetation
{
    public static partial class GrassPopulateInstancesKeys
    {
        public static readonly ValueParameterKey<Vector3> CameraPosition = ParameterKeys.NewValue<Vector3>();
        public static readonly ValueParameterKey<uint> Size = ParameterKeys.NewValue<uint>();
        public static readonly ValueParameterKey<uint> InstanceCount = ParameterKeys.NewValue<uint>();
        public static readonly ValueParameterKey<float> CellSize = ParameterKeys.NewValue<float>();
        public static readonly ValueParameterKey<float> FadeStartFraction = ParameterKeys.NewValue<float>();
        public static readonly ValueParameterKey<float> MinScale = ParameterKeys.NewValue<float>();
        public static readonly ValueParameterKey<float> MaxScale = ParameterKeys.NewValue<float>();
        public static readonly ValueParameterKey<Vector2> Seed = ParameterKeys.NewValue<Vector2>();
        public static readonly ValueParameterKey<bool> RotateAlongTerrainNormal = ParameterKeys.NewValue<bool>();
        public static readonly ValueParameterKey<float> Clumpiness = ParameterKeys.NewValue<float>(0.5f);
        public static readonly ValueParameterKey<float> ClumpSize = ParameterKeys.NewValue<float>(32.0f);
        public static readonly ValueParameterKey<uint> ValidBackgroundTexturesIds = ParameterKeys.NewValue<uint>();
        public static readonly ObjectParameterKey<Buffer> Instances = ParameterKeys.NewObject<Buffer>();
        public static readonly ObjectParameterKey<Buffer> InstancesCounter = ParameterKeys.NewObject<Buffer>();
    }
}
