// <auto-generated>
// Do not edit this file yourself!
//
// This code was generated by Stride Shader Mixin Code Generator.
// To generate it yourself, please install Stride.VisualStudio.Package .vsix
// and re-save the associated .sdfx.
// </auto-generated>

using System;
using Stride.Core;
using Stride.Rendering;
using Stride.Graphics;
using Stride.Shaders;
using Stride.Core.Mathematics;
using Buffer = Stride.Graphics.Buffer;

namespace StrideTerrain.Vegetation
{
    public static partial class GrassCullInstancesKeys
    {
        public static readonly ValueParameterKey<float> BoundingRadius = ParameterKeys.NewValue<float>();
        public static readonly ValueParameterKey<Vector4> FrustumPlanes = ParameterKeys.NewValue<Vector4>();
        public static readonly ObjectParameterKey<Buffer> Instances = ParameterKeys.NewObject<Buffer>();
        public static readonly ObjectParameterKey<Buffer> OutputWorld = ParameterKeys.NewObject<Buffer>();
        public static readonly ObjectParameterKey<Buffer> OutputWorldInverse = ParameterKeys.NewObject<Buffer>();
    }
}
