<Project Sdk="Microsoft.NET.Sdk">
	<Import Project="..\Common.props" />
	
	<PropertyGroup>
		<TargetFrameworks>net8.0-windows</TargetFrameworks>
		<Nullable>enable</Nullable>
		<AllowUnsafeBlocks>true</AllowUnsafeBlocks>
		<Configurations>Debug;Release;DebugExGameEditor</Configurations>
	</PropertyGroup>
	
	<ItemGroup>
		<PackageReference Include="Stride.Engine" />

		<PackageReference Include="Stride.Video" />
		<PackageReference Include="Stride.Physics" />
		<PackageReference Include="Stride.Navigation" />
		<PackageReference Include="Stride.Particles" />
		<PackageReference Include="Stride.UI" />

		<PackageReference Include="Stride.Core.Assets.CompilerApp" IncludeAssets="build;buildTransitive" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\StrideCommunity.ImGuiDebug\StrideCommunity.ImGuiDebug.csproj" />
		<ProjectReference Include="..\StrideTerrain.Common\StrideTerrain.Common.csproj" />
	</ItemGroup>

	<!-- Editor only references -->
	<ItemGroup Condition="$([System.Text.RegularExpressions.Regex]::IsMatch($(DefineConstants), '^(.*;)*GAME_EDITOR(;.*)*$'))">
	</ItemGroup>
	
	<ItemGroup>
	  <Compile Update="Rendering\Effects\CompressBC3.sdsl.cs">
	    <DesignTimeSharedInput>True</DesignTimeSharedInput>
	    <DesignTime>True</DesignTime>
	    <AutoGen>True</AutoGen>
	  </Compile>
	  <Compile Update="Rendering\Effects\CompressBC1.sdsl.cs">
	    <DesignTimeSharedInput>True</DesignTimeSharedInput>
	    <DesignTime>True</DesignTime>
	    <AutoGen>True</AutoGen>
	  </Compile>
	  <Compile Update="Rendering\Effects\BlockCompression.sdsl.cs">
	    <DesignTimeSharedInput>True</DesignTimeSharedInput>
	    <DesignTime>True</DesignTime>
	    <AutoGen>True</AutoGen>
	  </Compile>
	  <Compile Update="Rendering\Effects\CompressBC5.sdsl.cs">
	    <DesignTime>True</DesignTime>
	    <DesignTimeSharedInput>True</DesignTimeSharedInput>
	    <AutoGen>True</AutoGen>
	  </Compile>
	  <Compile Update="Rendering\Effects\PostEffectCommon.sdsl.cs">
	    <DesignTimeSharedInput>True</DesignTimeSharedInput>
	    <DesignTime>True</DesignTime>
	    <AutoGen>True</AutoGen>
	  </Compile>
	  <Compile Update="Rendering\Effects\HistogramReduce.sdsl.cs">
	    <DesignTimeSharedInput>True</DesignTimeSharedInput>
	    <DesignTime>True</DesignTime>
	    <AutoGen>True</AutoGen>
	  </Compile>
	  <Compile Update="Rendering\Effects\HistogramDrawDebug.sdsl.cs">
	    <DesignTimeSharedInput>True</DesignTimeSharedInput>
	    <DesignTime>True</DesignTime>
	    <AutoGen>True</AutoGen>
	  </Compile>
	  <Compile Update="Rendering\Effects\Histogram.sdsl.cs">
	    <DesignTimeSharedInput>True</DesignTimeSharedInput>
	    <DesignTime>True</DesignTime>
	    <AutoGen>True</AutoGen>
	  </Compile>
	  <Compile Update="Rendering\Effects\ExposureCommon.sdsl.cs">
	    <DesignTimeSharedInput>True</DesignTimeSharedInput>
	    <DesignTime>True</DesignTime>
	    <AutoGen>True</AutoGen>
	  </Compile>
	  <Compile Update="Rendering\Effects\BloomUpSample.sdsl.cs">
	    <DesignTimeSharedInput>True</DesignTimeSharedInput>
	    <DesignTime>True</DesignTime>
	    <AutoGen>True</AutoGen>
	  </Compile>
	  <Compile Update="Rendering\Effects\BloomDownSample.sdsl.cs">
	    <DesignTimeSharedInput>True</DesignTimeSharedInput>
	    <DesignTime>True</DesignTime>
	    <AutoGen>True</AutoGen>
	  </Compile>
	  <Compile Update="Rendering\Effects\BloomBrightPass.sdsl.cs">
	    <DesignTime>True</DesignTime>
	    <DesignTimeSharedInput>True</DesignTimeSharedInput>
	    <AutoGen>True</AutoGen>
	  </Compile>
	  <Compile Update="Rendering\Effects\FullscreenTriangle.sdsl.cs">
	    <DesignTimeSharedInput>True</DesignTimeSharedInput>
	    <DesignTime>True</DesignTime>
	    <AutoGen>True</AutoGen>
	  </Compile>
	  <Compile Update="Rendering\Effects\ToneMapASEC.sdsl.cs">
	    <DesignTime>True</DesignTime>
	    <DesignTimeSharedInput>True</DesignTimeSharedInput>
	    <AutoGen>True</AutoGen>
	  </Compile>
	  <Compile Update="TerrainSystem\Effects\Material\TerrainDisplacement.sdsl.cs">
	    <DesignTimeSharedInput>True</DesignTimeSharedInput>
	    <DesignTime>True</DesignTime>
	    <AutoGen>True</AutoGen>
	  </Compile>
	  <Compile Update="TerrainSystem\Effects\Material\TerrainMaterialSampling.sdsl.cs">
	    <DesignTimeSharedInput>True</DesignTimeSharedInput>
	    <DesignTime>True</DesignTime>
	    <AutoGen>True</AutoGen>
	    <DependentUpon>TerrainMaterialSampling.sdsl</DependentUpon>
	  </Compile>
	  <Compile Update="TerrainSystem\Effects\Material\TerrainMaterialDiffuseTileRenderer.sdsl.cs">
	    <DesignTimeSharedInput>True</DesignTimeSharedInput>
	    <DesignTime>True</DesignTime>
	    <AutoGen>True</AutoGen>
	  </Compile>
	  <Compile Update="TerrainSystem\Effects\Material\TerrainMaterialTileRenderer.sdsl.cs">
	    <DesignTime>True</DesignTime>
	    <DesignTimeSharedInput>True</DesignTimeSharedInput>
	    <AutoGen>True</AutoGen>
	  </Compile>
	  <Compile Update="TerrainSystem\Effects\Material\MaterialTerrainDisplacement.sdsl.cs">
	    <DesignTime>True</DesignTime>
	    <DesignTimeSharedInput>True</DesignTimeSharedInput>
	    <AutoGen>True</AutoGen>
	  </Compile>
	  <Compile Update="TerrainSystem\Effects\Material\TerrainComputeColorNormal.sdsl.cs">
	    <DesignTime>True</DesignTime>
	    <DesignTimeSharedInput>True</DesignTimeSharedInput>
	    <AutoGen>True</AutoGen>
	  </Compile>
	  <Compile Update="TerrainSystem\Effects\Material\TerrainMaterialStreamInitializer.sdsl.cs">
	    <DesignTime>True</DesignTime>
	    <DesignTimeSharedInput>True</DesignTimeSharedInput>
	    <AutoGen>True</AutoGen>
	  </Compile>
	  <Compile Update="TerrainSystem\Effects\Material\TerrainMaterialStreams.sdsl.cs">
	    <DesignTime>True</DesignTime>
	    <DesignTimeSharedInput>True</DesignTimeSharedInput>
	    <AutoGen>True</AutoGen>
	  </Compile>
	  <Compile Update="TerrainSystem\Effects\Material\TerrainVirtualTextureSampling.sdsl.cs">
	    <DesignTimeSharedInput>True</DesignTimeSharedInput>
	    <DesignTime>True</DesignTime>
	    <AutoGen>True</AutoGen>
	  </Compile>
	  <Compile Update="TerrainSystem\Effects\Material\TerrainVirtualTextureFeedback.sdsl.cs">
	    <DesignTimeSharedInput>True</DesignTimeSharedInput>
	    <DesignTime>True</DesignTime>
	    <AutoGen>True</AutoGen>
	  </Compile>
	  <Compile Update="TerrainSystem\Effects\Material\TerrainVirtualTexture.sdsl.cs">
	    <DesignTime>True</DesignTime>
	    <DesignTimeSharedInput>True</DesignTimeSharedInput>
	    <AutoGen>True</AutoGen>
	    <DependentUpon>TerrainVirtualTexture.sdsl</DependentUpon>
	  </Compile>
	  <Compile Update="TerrainSystem\Effects\Shadows\TerrainShadowBase.sdsl.cs">
	    <DesignTime>True</DesignTime>
	    <DesignTimeSharedInput>True</DesignTimeSharedInput>
	    <AutoGen>True</AutoGen>
	  </Compile>
	  <Compile Update="TerrainSystem\Effects\Shadows\TerrainShadowGenerator.sdsl.cs">
	    <DesignTime>True</DesignTime>
	    <DesignTimeSharedInput>True</DesignTimeSharedInput>
	    <AutoGen>True</AutoGen>
	  </Compile>
	  <Compile Update="TerrainSystem\Effects\TerrainData.sdsl.cs">
	    <DesignTime>True</DesignTime>
	    <DesignTimeSharedInput>True</DesignTimeSharedInput>
	    <AutoGen>True</AutoGen>
	  </Compile>
	  <Compile Update="TerrainSystem\Effects\TerrainQuery.sdsl.cs">
	    <DesignTime>True</DesignTime>
	    <DesignTimeSharedInput>True</DesignTimeSharedInput>
	    <AutoGen>True</AutoGen>
	  </Compile>
	  <Compile Update="TerrainSystem\Effects\TerrainStreams.sdsl.cs">
	    <DesignTime>True</DesignTime>
	    <DesignTimeSharedInput>True</DesignTimeSharedInput>
	    <AutoGen>True</AutoGen>
	  </Compile>
	  <Compile Update="Vegetation\Effects\SetupIndirectDispatchArgs.sdsl.cs">
	    <DesignTimeSharedInput>True</DesignTimeSharedInput>
	    <DesignTime>True</DesignTime>
	    <AutoGen>True</AutoGen>
	    <DependentUpon>SetupIndirectDispatchArgs.sdsl</DependentUpon>
	  </Compile>
	  <Compile Update="Vegetation\Effects\ClearDrawArgs.sdsl.cs">
	    <DesignTime>True</DesignTime>
	    <DesignTimeSharedInput>True</DesignTimeSharedInput>
	    <AutoGen>True</AutoGen>
	  </Compile>
	  <Compile Update="Vegetation\Effects\ComoputeColorImpostor.sdsl.cs">
	    <DesignTime>True</DesignTime>
	    <DesignTimeSharedInput>True</DesignTimeSharedInput>
	    <AutoGen>True</AutoGen>
	  </Compile>
	  <Compile Update="Vegetation\Effects\GrassCullInstances.sdsl.cs">
	    <DesignTimeSharedInput>True</DesignTimeSharedInput>
	    <DesignTime>True</DesignTime>
	    <AutoGen>True</AutoGen>
	  </Compile>
	  <Compile Update="Vegetation\Effects\GrassPopulateInstances.sdsl.cs">
	    <DesignTime>True</DesignTime>
	    <DesignTimeSharedInput>True</DesignTimeSharedInput>
	    <AutoGen>True</AutoGen>
	  </Compile>
	  <Compile Update="Vegetation\Effects\MaterialGrassDisplacementFeature.sdsl.cs">
	    <DesignTime>True</DesignTime>
	    <DesignTimeSharedInput>True</DesignTimeSharedInput>
	    <AutoGen>True</AutoGen>
	  </Compile>
	  <Compile Update="Vegetation\Effects\MaterialImpostorDisplacementFeature.sdsl.cs">
	    <DesignTime>True</DesignTime>
	    <DesignTimeSharedInput>True</DesignTimeSharedInput>
	    <AutoGen>True</AutoGen>
	    <DependentUpon>MaterialImpostorDisplacementFeature.sdsl</DependentUpon>
	  </Compile>
	  <Compile Update="Vegetation\Effects\MaterialTreeDisplacementFeature.sdsl.cs">
	    <DesignTime>True</DesignTime>
	    <DesignTimeSharedInput>True</DesignTimeSharedInput>
	    <AutoGen>True</AutoGen>
	  </Compile>
	  <Compile Update="Vegetation\Effects\MaterialVegetationSurfaceSubsurfaceScatteringShading.sdsl.cs">
	    <DesignTime>True</DesignTime>
	    <DesignTimeSharedInput>True</DesignTimeSharedInput>
	    <AutoGen>True</AutoGen>
	  </Compile>
	  <Compile Update="Weather\Effects\Atmosphere\AtmosphereBase.sdsl.cs">
	    <DesignTime>True</DesignTime>
	    <DesignTimeSharedInput>True</DesignTimeSharedInput>
	    <AutoGen>True</AutoGen>
	  </Compile>
	  <Compile Update="Weather\Effects\Atmosphere\AtmosphereRenderSky.sdsl.cs">
	    <DesignTime>True</DesignTime>
	    <DesignTimeSharedInput>True</DesignTimeSharedInput>
	    <AutoGen>True</AutoGen>
	  </Compile>
	  <Compile Update="Weather\Effects\Atmosphere\LUT\AtmosphereCameraVolumeLut.sdsl.cs">
	    <DesignTime>True</DesignTime>
	    <DesignTimeSharedInput>True</DesignTimeSharedInput>
	    <AutoGen>True</AutoGen>
	  </Compile>
	  <Compile Update="Weather\Effects\Lights\VolumetricLightDiretional.sdsl.cs">
	    <DesignTime>True</DesignTime>
	    <DesignTimeSharedInput>True</DesignTimeSharedInput>
	    <AutoGen>True</AutoGen>
	  </Compile>
	  <Compile Update="Weather\Effects\Lights\VolumetricLightDiretionalBase.sdsl.cs">
	    <DesignTime>True</DesignTime>
	    <DesignTimeSharedInput>True</DesignTimeSharedInput>
	    <AutoGen>True</AutoGen>
	  </Compile>
	  <Compile Update="Weather\Effects\Lights\VolumetricLightDiretionalEffect.sdfx.cs">
	    <DesignTime>True</DesignTime>
	    <DesignTimeSharedInput>True</DesignTimeSharedInput>
	    <AutoGen>True</AutoGen>
	  </Compile>
	  <Compile Update="Weather\Effects\WeatherFordwardRenderer.sdsl.cs">
	    <DesignTime>True</DesignTime>
	    <DesignTimeSharedInput>True</DesignTimeSharedInput>
	    <AutoGen>True</AutoGen>
	  </Compile>
	</ItemGroup>
	<ItemGroup>
	  <None Update="Rendering\Effects\CompressBC3.sdsl">
	    <LastGenOutput>CompressBC3.sdsl.cs</LastGenOutput>
	  </None>
	  <None Update="Rendering\Effects\CompressBC5.sdsl">
	    <LastGenOutput>CompressBC5.sdsl.cs</LastGenOutput>
	  </None>
	  <None Update="Rendering\Effects\CompressBC1.sdsl">
	    <LastGenOutput>CompressBC1.sdsl.cs</LastGenOutput>
	  </None>
	  <None Update="Rendering\Effects\BlockCompression.sdsl">
	    <LastGenOutput>BlockCompression.sdsl.cs</LastGenOutput>
	  </None>
	  <None Update="Rendering\Effects\PostEffectCommon.sdsl">
	    <LastGenOutput>PostEffectCommon.sdsl.cs</LastGenOutput>
	  </None>
	  <None Update="Rendering\Effects\HistogramReduce.sdsl">
	    <LastGenOutput>HistogramReduce.sdsl.cs</LastGenOutput>
	  </None>
	  <None Update="Rendering\Effects\HistogramDrawDebug.sdsl">
	    <LastGenOutput>HistogramDrawDebug.sdsl.cs</LastGenOutput>
	  </None>
	  <None Update="Rendering\Effects\Histogram.sdsl">
	    <LastGenOutput>Histogram.sdsl.cs</LastGenOutput>
	  </None>
	  <None Update="Rendering\Effects\ExposureCommon.sdsl">
	    <LastGenOutput>ExposureCommon.sdsl.cs</LastGenOutput>
	  </None>
	  <None Update="Rendering\Effects\BloomUpSample.sdsl">
	    <LastGenOutput>BloomUpSample.sdsl.cs</LastGenOutput>
	  </None>
	  <None Update="Rendering\Effects\BloomDownSample.sdsl">
	    <LastGenOutput>BloomDownSample.sdsl.cs</LastGenOutput>
	  </None>
	  <None Update="Rendering\Effects\BloomBrightPass.sdsl">
	    <LastGenOutput>BloomBrightPass.sdsl.cs</LastGenOutput>
	  </None>
	  <None Update="Rendering\Effects\FullscreenTriangle.sdsl">
	    <LastGenOutput>FullscreenTriangle.sdsl.cs</LastGenOutput>
	  </None>
	  <None Update="Rendering\Effects\ToneMapASEC.sdsl">
	    <LastGenOutput>ToneMapASEC.sdsl.cs</LastGenOutput>
	  </None>
	  <None Update="TerrainSystem\Effects\Material\TerrainDisplacement.sdsl">
	    <LastGenOutput>TerrainDisplacement.sdsl.cs</LastGenOutput>
	  </None>
	  <None Update="TerrainSystem\Effects\Material\TerrainMaterialSampling.sdsl">
	    <LastGenOutput>TerrainMaterialSampling.sdsl.cs</LastGenOutput>
	  </None>
	  <None Update="TerrainSystem\Effects\Material\TerrainMaterialDiffuseTileRenderer.sdsl">
	    <LastGenOutput>TerrainMaterialDiffuseTileRenderer.sdsl.cs</LastGenOutput>
	  </None>
	  <None Update="TerrainSystem\Effects\Material\TerrainMaterialTileRenderer.sdsl">
	    <LastGenOutput>TerrainMaterialTileRenderer.sdsl.cs</LastGenOutput>
	  </None>
	  <None Update="TerrainSystem\Effects\Material\MaterialTerrainDisplacement.sdsl">
	    <LastGenOutput>MaterialTerrainDisplacement.sdsl.cs</LastGenOutput>
	  </None>
	  <None Update="TerrainSystem\Effects\Material\TerrainComputeColorNormal.sdsl">
	    <LastGenOutput>TerrainComputeColorNormal.sdsl.cs</LastGenOutput>
	  </None>
	  <None Update="TerrainSystem\Effects\Material\TerrainMaterialStreamInitializer.sdsl">
	    <LastGenOutput>TerrainMaterialStreamInitializer.sdsl.cs</LastGenOutput>
	  </None>
	  <None Update="TerrainSystem\Effects\Material\TerrainMaterialStreams.sdsl">
	    <LastGenOutput>TerrainMaterialStreams.sdsl.cs</LastGenOutput>
	  </None>
	  <None Update="TerrainSystem\Effects\Material\TerrainVirtualTextureSampling.sdsl">
	    <LastGenOutput>TerrainVirtualTextureSampling.sdsl.cs</LastGenOutput>
	  </None>
	  <None Update="TerrainSystem\Effects\Material\TerrainVirtualTextureFeedback.sdsl">
	    <LastGenOutput>TerrainVirtualTextureFeedback.sdsl.cs</LastGenOutput>
	  </None>
	  <None Update="TerrainSystem\Effects\Material\TerrainVirtualTexture.sdsl">
	    <LastGenOutput>TerrainVirtualTexture.sdsl.cs</LastGenOutput>
	  </None>
	  <None Update="TerrainSystem\Effects\Shadows\TerrainShadowBase.sdsl">
	    <LastGenOutput>TerrainShadowBase.sdsl.cs</LastGenOutput>
	  </None>
	  <None Update="TerrainSystem\Effects\Shadows\TerrainShadowGenerator.sdsl">
	    <LastGenOutput>TerrainShadowGenerator.sdsl.cs</LastGenOutput>
	  </None>
	  <None Update="TerrainSystem\Effects\TerrainData.sdsl">
	    <LastGenOutput>TerrainData.sdsl.cs</LastGenOutput>
	  </None>
	  <None Update="TerrainSystem\Effects\TerrainQuery.sdsl">
	    <LastGenOutput>TerrainQuery.sdsl.cs</LastGenOutput>
	  </None>
	  <None Update="TerrainSystem\Effects\TerrainStreams.sdsl">
	    <LastGenOutput>TerrainStreams.sdsl.cs</LastGenOutput>
	  </None>
	  <None Update="Vegetation\Effects\SetupIndirectDispatchArgs.sdsl">
	    <LastGenOutput>SetupIndirectDispatchArgs.sdsl.cs</LastGenOutput>
	  </None>
	  <None Update="Vegetation\Effects\ClearDrawArgs.sdsl">
	    <LastGenOutput>ClearDrawArgs.sdsl.cs</LastGenOutput>
	  </None>
	  <None Update="Vegetation\Effects\ComoputeColorImpostor.sdsl">
	    <LastGenOutput>ComoputeColorImpostor.sdsl.cs</LastGenOutput>
	  </None>
	  <None Update="Vegetation\Effects\GrassCullInstances.sdsl">
	    <LastGenOutput>GrassCullInstances.sdsl.cs</LastGenOutput>
	  </None>
	  <None Update="Vegetation\Effects\GrassPopulateInstances.sdsl">
	    <LastGenOutput>GrassPopulateInstances.sdsl.cs</LastGenOutput>
	  </None>
	  <None Update="Vegetation\Effects\MaterialGrassDisplacementFeature.sdsl">
	    <LastGenOutput>MaterialGrassDisplacementFeature.sdsl.cs</LastGenOutput>
	  </None>
	  <None Update="Vegetation\Effects\MaterialImpostorDisplacementFeature.sdsl">
	    <LastGenOutput>MaterialImpostorDisplacementFeature.sdsl.cs</LastGenOutput>
	  </None>
	  <None Update="Vegetation\Effects\MaterialTreeDisplacementFeature.sdsl">
	    <LastGenOutput>MaterialTreeDisplacementFeature.sdsl.cs</LastGenOutput>
	  </None>
	  <None Update="Vegetation\Effects\MaterialVegetationSurfaceSubsurfaceScatteringShading.sdsl">
	    <LastGenOutput>MaterialVegetationSurfaceSubsurfaceScatteringShading.sdsl.cs</LastGenOutput>
	  </None>
	  <None Update="Weather\Effects\Atmosphere\AtmosphereBase.sdsl">
	    <LastGenOutput>AtmosphereBase.sdsl.cs</LastGenOutput>
	  </None>
	  <None Update="Weather\Effects\Atmosphere\AtmosphereRenderSky.sdsl">
	    <LastGenOutput>AtmosphereRenderSky.sdsl.cs</LastGenOutput>
	  </None>
	  <None Update="Weather\Effects\Atmosphere\LUT\AtmosphereCameraVolumeLut.sdsl">
	    <LastGenOutput>AtmosphereCameraVolumeLut.sdsl.cs</LastGenOutput>
	  </None>
	  <None Update="Weather\Effects\Lights\VolumetricLightDiretional.sdsl">
	    <LastGenOutput>VolumetricLightDiretional.sdsl.cs</LastGenOutput>
	  </None>
	  <None Update="Weather\Effects\Lights\VolumetricLightDiretionalBase.sdsl">
	    <LastGenOutput>VolumetricLightDiretionalBase.sdsl.cs</LastGenOutput>
	    <Generator>StrideShaderKeyGenerator</Generator>
	  </None>
	  <None Update="Weather\Effects\Lights\VolumetricLightDiretionalEffect.sdfx">
	    <LastGenOutput>VolumetricLightDiretionalEffect.sdfx.cs</LastGenOutput>
	  </None>
	  <None Update="Weather\Effects\WeatherFordwardRenderer.sdsl">
	    <LastGenOutput>WeatherFordwardRenderer.sdsl.cs</LastGenOutput>
	  </None>
	</ItemGroup>
</Project>
