<Project Sdk="Microsoft.NET.Sdk">
	<Import Project="..\Common.props" />
	
	<PropertyGroup>
		<TargetFrameworks>net10.0-windows</TargetFrameworks>
		<Nullable>enable</Nullable>
		<AllowUnsafeBlocks>true</AllowUnsafeBlocks>
		<Configurations>Debug;Release;DebugExGameEditor</Configurations>
	</PropertyGroup>
	
	<ItemGroup>
		<PackageReference Include="Stride.Engine" />

		<PackageReference Include="Stride.Video" />
		<PackageReference Include="Stride.Physics" />
		<PackageReference Include="Stride.Navigation" />
		<PackageReference Include="Stride.Particles" />
		<PackageReference Include="Stride.UI" />

		<PackageReference Include="Stride.AssetCompiler" IncludeAssets="build;buildTransitive" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\StrideCommunity.ImGuiDebug\StrideCommunity.ImGuiDebug.csproj" />
		<ProjectReference Include="..\StrideTerrain.Common\StrideTerrain.Common.csproj" />
	</ItemGroup>

	<!-- Editor only references -->
	<ItemGroup Condition="$([System.Text.RegularExpressions.Regex]::IsMatch($(DefineConstants), '^(.*;)*GAME_EDITOR(;.*)*$'))">
	</ItemGroup>
	
	<ItemGroup>
	  <None Update="Rendering\Effects\CompressBC3.sdsl" />
	  <None Update="Rendering\Effects\CompressBC5.sdsl" />
	  <None Update="Rendering\Effects\CompressBC1.sdsl" />
	  <None Update="Rendering\Effects\BlockCompression.sdsl" />
	  <None Update="Rendering\Effects\PostEffectCommon.sdsl" />
	  <None Update="Rendering\Effects\HistogramReduce.sdsl" />
	  <None Update="Rendering\Effects\HistogramDrawDebug.sdsl" />
	  <None Update="Rendering\Effects\Histogram.sdsl" />
	  <None Update="Rendering\Effects\ExposureCommon.sdsl" />
	  <None Update="Rendering\Effects\BloomUpSample.sdsl" />
	  <None Update="Rendering\Effects\BloomDownSample.sdsl" />
	  <None Update="Rendering\Effects\BloomBrightPass.sdsl" />
	  <None Update="Rendering\Effects\FullscreenTriangle.sdsl" />
	  <None Update="Rendering\Effects\ToneMapASEC.sdsl" />
	  <None Update="TerrainSystem\Effects\Material\TerrainDisplacement.sdsl" />
	  <None Update="TerrainSystem\Effects\Material\TerrainMaterialSampling.sdsl" />
	  <None Update="TerrainSystem\Effects\Material\TerrainMaterialDiffuseTileRenderer.sdsl" />
	  <None Update="TerrainSystem\Effects\Material\TerrainMaterialTileRenderer.sdsl" />
	  <None Update="TerrainSystem\Effects\Material\MaterialTerrainDisplacement.sdsl" />
	  <None Update="TerrainSystem\Effects\Material\TerrainComputeColorNormal.sdsl" />
	  <None Update="TerrainSystem\Effects\Material\TerrainMaterialStreamInitializer.sdsl" />
	  <None Update="TerrainSystem\Effects\Material\TerrainMaterialStreams.sdsl" />
	  <None Update="TerrainSystem\Effects\Material\TerrainVirtualTextureSampling.sdsl" />
	  <None Update="TerrainSystem\Effects\Material\TerrainVirtualTextureFeedback.sdsl" />
	  <None Update="TerrainSystem\Effects\Material\TerrainVirtualTexture.sdsl" />
	  <None Update="TerrainSystem\Effects\Shadows\TerrainShadowBase.sdsl" />
	  <None Update="TerrainSystem\Effects\Shadows\TerrainShadowGenerator.sdsl" />
	  <None Update="TerrainSystem\Effects\TerrainData.sdsl" />
	  <None Update="TerrainSystem\Effects\TerrainQuery.sdsl" />
	  <None Update="TerrainSystem\Effects\TerrainStreams.sdsl" />
	  <None Update="Vegetation\Effects\SetupIndirectDispatchArgs.sdsl" />
	  <None Update="Vegetation\Effects\ClearDrawArgs.sdsl" />
	  <None Update="Vegetation\Effects\ComoputeColorImpostor.sdsl" />
	  <None Update="Vegetation\Effects\GrassCullInstances.sdsl" />
	  <None Update="Vegetation\Effects\GrassPopulateInstances.sdsl" />
	  <None Update="Vegetation\Effects\MaterialGrassDisplacementFeature.sdsl" />
	  <None Update="Vegetation\Effects\MaterialImpostorDisplacementFeature.sdsl" />
	  <None Update="Vegetation\Effects\MaterialTreeDisplacementFeature.sdsl" />
	  <None Update="Vegetation\Effects\MaterialVegetationSurfaceSubsurfaceScatteringShading.sdsl" />
	  <None Update="Weather\Effects\Atmosphere\Atmosphere.sdfx" />
	  <None Update="Weather\Effects\Atmosphere\AtmosphereBase.sdsl" />
	  <None Update="Weather\Effects\Atmosphere\AtmosphereParametersBase.sdsl" />
	  <None Update="Weather\Effects\Atmosphere\AtmosphereRenderAerialPerspective.sdsl" />
	  <None Update="Weather\Effects\Atmosphere\AtmosphereRenderSky.sdsl" />
	  <None Update="Weather\Effects\Atmosphere\CloudBase.sdsl" />
	  <None Update="Weather\Effects\Atmosphere\CloudBasicNoise.sdsl" />
	  <None Update="Weather\Effects\Atmosphere\CloudDetailNoise.sdsl" />
	  <None Update="Weather\Effects\Atmosphere\CloudReconstruct.sdsl" />
	  <None Update="Weather\Effects\Atmosphere\CloudWeatherMap.sdsl" />
	  <None Update="Weather\Effects\Atmosphere\LUT\AtmosphereCameraVolumeLut.sdsl" />
	  <None Update="Weather\Effects\Atmosphere\Noise.sdsl" />
	  <None Update="Weather\Effects\Atmosphere\VolumetricClouds.sdsl" />
	  <None Update="Weather\Effects\Atmosphere\VolumetricCloudsTrace.sdsl" />
	  <None Update="Weather\Effects\Lights\VolumetricLightDiretional.sdsl" />
	  <None Update="Weather\Effects\Lights\VolumetricLightDiretionalBase.sdsl" />
	  <None Update="Weather\Effects\Lights\VolumetricLightDiretionalEffect.sdfx" />
	  <None Update="Weather\Effects\WeatherFordwardRenderer.sdsl" />
	  <None Update="Weather\Effects\WeatherForwardRendererBase.sdsl" />
	  <None Update="Weather\Effects\WeatherForwardShadingEffect.sdfx" />
	  <None Update="Weather\Effects\WeatherLightDirectionalGroup.sdsl" />
	</ItemGroup>
</Project>
