// <auto-generated>
// Do not edit this file yourself!
//
// This code was generated by Stride Shader Mixin Code Generator.
// To generate it yourself, please install Stride.VisualStudio.Package .vsix
// and re-save the associated .sdfx.
// </auto-generated>

using System;
using Stride.Core;
using Stride.Rendering;
using Stride.Graphics;
using Stride.Shaders;
using Stride.Core.Mathematics;
using Buffer = Stride.Graphics.Buffer;

namespace StrideTerrain.Weather.Effects.Lights
{
    public static partial class AtmosphereCubeMapEnvironmentColorKeys
    {
        public static readonly ValueParameterKey<float> MipCount = ParameterKeys.NewValue<float>();
        public static readonly ValueParameterKey<float> Intensity = ParameterKeys.NewValue<float>();
        public static readonly ValueParameterKey<bool> IsRenderingCubeMap = ParameterKeys.NewValue<bool>();
        public static readonly ObjectParameterKey<Texture> CubeMap = ParameterKeys.NewObject<Texture>();
    }
}
