// <auto-generated>
// Do not edit this file yourself!
//
// This code was generated by Stride Shader Mixin Code Generator.
// To generate it yourself, please install Stride.VisualStudio.Package .vsix
// and re-save the associated .sdfx.
// </auto-generated>

using System;
using Stride.Core;
using Stride.Rendering;
using Stride.Graphics;
using Stride.Shaders;
using Stride.Core.Mathematics;
using Buffer = Stride.Graphics.Buffer;

namespace StrideTerrain.Editor.Effects
{
    public static partial class LayerRidgedKeys
    {
        public static readonly ValueParameterKey<float> Frequency = ParameterKeys.NewValue<float>();
        public static readonly ValueParameterKey<float> Amplitude = ParameterKeys.NewValue<float>();
        public static readonly ValueParameterKey<int> Octaves = ParameterKeys.NewValue<int>();
        public static readonly ValueParameterKey<float> Lacunarity = ParameterKeys.NewValue<float>();
        public static readonly ValueParameterKey<float> Gain = ParameterKeys.NewValue<float>();
        public static readonly ValueParameterKey<float> Scale = ParameterKeys.NewValue<float>();
    }
}
