// <auto-generated>
// Do not edit this file yourself!
//
// This code was generated by Stride Shader Mixin Code Generator.
// To generate it yourself, please install Stride.VisualStudio.Package .vsix
// and re-save the associated .sdfx.
// </auto-generated>

using System;
using Stride.Core;
using Stride.Rendering;
using Stride.Graphics;
using Stride.Shaders;
using Stride.Core.Mathematics;
using Buffer = Stride.Graphics.Buffer;

namespace StrideTerrain.Editor.Effects
{
    public static partial class LayerErosionKeys
    {
        public static readonly ObjectParameterKey<Buffer> RandomIndices = ParameterKeys.NewObject<Buffer>();
        public static readonly ObjectParameterKey<Buffer> BrushIndices = ParameterKeys.NewObject<Buffer>();
        public static readonly ObjectParameterKey<Buffer> BrushWeights = ParameterKeys.NewObject<Buffer>();
        public static readonly ValueParameterKey<int> BrushLength = ParameterKeys.NewValue<int>();
        public static readonly ValueParameterKey<int> BorderSize = ParameterKeys.NewValue<int>();
        public static readonly ValueParameterKey<int> MaxLifetime = ParameterKeys.NewValue<int>();
        public static readonly ValueParameterKey<float> Inertia = ParameterKeys.NewValue<float>();
        public static readonly ValueParameterKey<float> SedimentCapacityFactor = ParameterKeys.NewValue<float>();
        public static readonly ValueParameterKey<float> MinSedimentCapacity = ParameterKeys.NewValue<float>();
        public static readonly ValueParameterKey<float> DepositSpeed = ParameterKeys.NewValue<float>();
        public static readonly ValueParameterKey<float> ErodeSpeed = ParameterKeys.NewValue<float>();
        public static readonly ValueParameterKey<float> EvaporateSpeed = ParameterKeys.NewValue<float>();
        public static readonly ValueParameterKey<float> Gravity = ParameterKeys.NewValue<float>();
        public static readonly ValueParameterKey<float> StartSpeed = ParameterKeys.NewValue<float>();
        public static readonly ValueParameterKey<float> StartWater = ParameterKeys.NewValue<float>();
    }
}
