<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>net10.0-windows</TargetFrameworks>
	  <ProduceReferenceAssembly>false</ProduceReferenceAssembly>
	  <Configurations>Debug;Release;DebugExGameEditor</Configurations>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Stride.Engine" PrivateAssets="contentfiles;analyzers" />

    <PackageReference Include="Stride.Video" PrivateAssets="contentfiles;analyzers" />
    <PackageReference Include="Stride.Physics" PrivateAssets="contentfiles;analyzers" />
    <PackageReference Include="Stride.Navigation" PrivateAssets="contentfiles;analyzers" />
    <PackageReference Include="Stride.Particles" PrivateAssets="contentfiles;analyzers" />
    <PackageReference Include="Stride.UI" PrivateAssets="contentfiles;analyzers" />
    <PackageReference Include="Stride.Core" PrivateAssets="contentfiles;analyzers" />

    <PackageReference Include="Stride.AssetCompiler" PrivateAssets="contentfiles;analyzers" IncludeAssets="build" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\TR.Stride.Common\TR.Stride.Common.csproj" />
  </ItemGroup>

  <ItemGroup>
    <None Update="Effects\MaterialOceanSurfaceEmissiveShading.sdsl" />
    <None Update="Effects\OceanCalculateConjugatedSpectrum.sdsl" />
    <None Update="Effects\OceanCalculateInitialSpectrum.sdsl" />
    <None Update="Effects\OceanDisplacement.sdsl" />
    <None Update="Effects\OceanEmissive.sdsl" />
    <None Update="Effects\OceanFastFourierTransformBase.sdsl" />
    <None Update="Effects\OceanFillResultTextures.sdsl" />
    <None Update="Effects\OceanGenerateMips.sdsl" />
    <None Update="Effects\OceanHorizontalStepFFT.sdsl" />
    <None Update="Effects\OceanHorizontalStepInverseFFT.sdsl" />
    <None Update="Effects\OceanInitialSpectrumCommon.sdsl" />
    <None Update="Effects\OceanPermute.sdsl" />
    <None Update="Effects\OceanPrecomputeTwiddleFactorsAndInputIndices.sdsl" />
    <None Update="Effects\OceanScale.sdsl" />
    <None Update="Effects\OceanShadingCommon.sdsl" />
    <None Update="Effects\OceanTimeDependentSpectrum.sdsl" />
    <None Update="Effects\OceanVerticalStepFFT.sdsl" />
    <None Update="Effects\OceanVerticalStepInverseFFT.sdsl" />
  </ItemGroup>
</Project>
