// <auto-generated>
// Do not edit this file yourself!
//
// This code was generated by Stride Shader Mixin Code Generator.
// To generate it yourself, please install Stride.VisualStudio.Package .vsix
// and re-save the associated .sdfx.
// </auto-generated>

using System;
using Stride.Core;
using Stride.Rendering;
using Stride.Graphics;
using Stride.Shaders;
using Stride.Core.Mathematics;
using Buffer = Stride.Graphics.Buffer;

namespace StrideTerrain.TerrainSystem.Effects.Material
{
    public static partial class TerrainMaterialDiffuseTileRendererKeys
    {
        public static readonly ValueParameterKey<Vector2> UvMin = ParameterKeys.NewValue<Vector2>();
        public static readonly ValueParameterKey<Vector2> UvMax = ParameterKeys.NewValue<Vector2>();
        public static readonly ValueParameterKey<Vector2> WorldBoundsMin = ParameterKeys.NewValue<Vector2>();
        public static readonly ValueParameterKey<Vector2> WorldBoundsMax = ParameterKeys.NewValue<Vector2>();
        public static readonly ValueParameterKey<int> AtlasSize = ParameterKeys.NewValue<int>();
        public static readonly ObjectParameterKey<Texture> TerrainControlMap = ParameterKeys.NewObject<Texture>();
        public static readonly ObjectParameterKey<Texture> DiffuseRoughnessArray = ParameterKeys.NewObject<Texture>();
    }
}
