// <auto-generated>
// Do not edit this file yourself!
//
// This code was generated by Stride Shader Mixin Code Generator.
// To generate it yourself, please install Stride.VisualStudio.Package .vsix
// and re-save the associated .sdfx.
// </auto-generated>

using System;
using Stride.Core;
using Stride.Rendering;
using Stride.Graphics;
using Stride.Shaders;
using Stride.Core.Mathematics;
using Buffer = Stride.Graphics.Buffer;

namespace StrideTerrain.TerrainSystem.Effects.Material
{
    public static partial class TerrainVirtualTextureKeys
    {
        public static readonly ValueParameterKey<float> VTMipBias = ParameterKeys.NewValue<float>();
        public static readonly ValueParameterKey<float> VTMaxAniso = ParameterKeys.NewValue<float>();
        public static readonly ValueParameterKey<float> VTResolution = ParameterKeys.NewValue<float>();
        public static readonly ValueParameterKey<Vector3> VTCameraPosition = ParameterKeys.NewValue<Vector3>();
        // Two mip origins packed per float4: Packed0.xy=mip0, .zw=mip1, ..., Packed4.xy=mip8
        public static readonly ValueParameterKey<Vector4> ClipmapOriginsPacked0 = ParameterKeys.NewValue<Vector4>();
        public static readonly ValueParameterKey<Vector4> ClipmapOriginsPacked1 = ParameterKeys.NewValue<Vector4>();
        public static readonly ValueParameterKey<Vector4> ClipmapOriginsPacked2 = ParameterKeys.NewValue<Vector4>();
        public static readonly ValueParameterKey<Vector4> ClipmapOriginsPacked3 = ParameterKeys.NewValue<Vector4>();
        public static readonly ValueParameterKey<Vector4> ClipmapOriginsPacked4 = ParameterKeys.NewValue<Vector4>();
    }
}
