// <auto-generated>
// Do not edit this file yourself!
//
// This code was generated by Stride Shader Mixin Code Generator.
// To generate it yourself, please install Stride.VisualStudio.Package .vsix
// and re-save the associated .sdfx.
// </auto-generated>

using System;
using Stride.Core;
using Stride.Rendering;
using Stride.Graphics;
using Stride.Shaders;
using Stride.Core.Mathematics;
using Buffer = Stride.Graphics.Buffer;

namespace StrideTerrain.Weather.Effects.Atmosphere
{
    [DataContract]public partial class AtmosphereEffectParameters : ShaderMixinParameters
    {
        public static readonly PermutationParameterKey<bool> RenderSun = ParameterKeys.NewPermutation<bool>(true);
        public static readonly PermutationParameterKey<bool> EnableHeightFog = ParameterKeys.NewPermutation<bool>(false);
    };
    internal static partial class ShaderMixins
    {
        internal partial class AtmosphereRenderSkyEffect  : IShaderMixinBuilder
        {
            public void Generate(ShaderMixinSource mixin, ShaderMixinContext context)
            {
                context.Mixin(mixin, "AtmosphereRenderSky", context.GetParam(AtmosphereEffectParameters.RenderSun), context.GetParam(AtmosphereEffectParameters.EnableHeightFog));
            }

            [System.Runtime.CompilerServices.ModuleInitializer]
            internal static void __Initialize__()

            {
                ShaderMixinManager.Register("AtmosphereRenderSkyEffect", new AtmosphereRenderSkyEffect());
            }
        }
    }
}
