// <auto-generated>
// Do not edit this file yourself!
//
// This code was generated by Stride Shader Mixin Code Generator.
// To generate it yourself, please install Stride.VisualStudio.Package .vsix
// and re-save the associated .sdfx.
// </auto-generated>

using System;
using Stride.Core;
using Stride.Rendering;
using Stride.Graphics;
using Stride.Shaders;
using Stride.Core.Mathematics;
using Buffer = Stride.Graphics.Buffer;

namespace StrideTerrain.Weather.Effects.Atmosphere
{
    public static partial class CloudWeatherMapKeys
    {
        public static readonly ObjectParameterKey<Texture> OutputTexture = ParameterKeys.NewObject<Texture>();
        public static readonly ValueParameterKey<uint> MapSize = ParameterKeys.NewValue<uint>();
        public static readonly ValueParameterKey<float> Coverage = ParameterKeys.NewValue<float>();
        public static readonly ValueParameterKey<float> CoverageScale = ParameterKeys.NewValue<float>();
        public static readonly ValueParameterKey<float> TypeScale = ParameterKeys.NewValue<float>();
        public static readonly ValueParameterKey<Vector2> WindOffset = ParameterKeys.NewValue<Vector2>();
    }
}
