// <auto-generated>
// Do not edit this file yourself!
//
// This code was generated by Stride Shader Mixin Code Generator.
// To generate it yourself, please install Stride.VisualStudio.Package .vsix
// and re-save the associated .sdfx.
// </auto-generated>

using System;
using Stride.Core;
using Stride.Rendering;
using Stride.Graphics;
using Stride.Shaders;
using Stride.Core.Mathematics;
using Buffer = Stride.Graphics.Buffer;

namespace StrideTerrain.Weather.Effects.Atmosphere
{
    public static partial class VolumetricCloudsTraceKeys
    {
        public static readonly ObjectParameterKey<Texture> TransmittanceLUT = ParameterKeys.NewObject<Texture>();
        public static readonly ObjectParameterKey<Texture> SkyLuminanceLUT = ParameterKeys.NewObject<Texture>();
        public static readonly ObjectParameterKey<Texture> HistoryTexture = ParameterKeys.NewObject<Texture>();
        public static readonly ObjectParameterKey<Texture> BasicNoiseTexture = ParameterKeys.NewObject<Texture>();
        public static readonly ObjectParameterKey<Texture> DetailNoiseTexture = ParameterKeys.NewObject<Texture>();
        public static readonly ObjectParameterKey<Texture> WeatherMapTexture = ParameterKeys.NewObject<Texture>();
        public static readonly ObjectParameterKey<Texture> OutputTexture = ParameterKeys.NewObject<Texture>();
        public static readonly ValueParameterKey<CloudParameters> Clouds = ParameterKeys.NewValue<CloudParameters>();
        public static readonly ValueParameterKey<AtmosphereParameters> Atmosphere = ParameterKeys.NewValue<AtmosphereParameters>();
        public static readonly ValueParameterKey<Matrix> InvViewProjection = ParameterKeys.NewValue<Matrix>();
        public static readonly ValueParameterKey<Matrix> PrevViewProjection = ParameterKeys.NewValue<Matrix>();
        public static readonly ValueParameterKey<Vector3> SunDirection = ParameterKeys.NewValue<Vector3>();
        public static readonly ValueParameterKey<Color3> SunColor = ParameterKeys.NewValue<Color3>();
        public static readonly ValueParameterKey<Vector3> CameraPosition = ParameterKeys.NewValue<Vector3>();
        public static readonly ValueParameterKey<Vector2> Resolution = ParameterKeys.NewValue<Vector2>();
        public static readonly ValueParameterKey<uint> FrameIndex = ParameterKeys.NewValue<uint>();
        public static readonly ValueParameterKey<float> TemporalBlendFactor = ParameterKeys.NewValue<float>();
    }
}
